export const languages=[
    {
        name:"HTML",
        backgroundColor:"#E2680F",
        color:"#F9F4DA"
    },
     {
        name:"CSS",
        backgroundColor:"#328AF1",
        color:"#F9F4DA"
    },
     {
        name:"Javascript",
        backgroundColor:"#f34b7d",
        color:"#F9F4DA"
    },
     {
        name:"React",
        backgroundColor:"#b07219",
        color:"#F9F4DA"
    },
     {
        name:"Typescript",
        backgroundColor:"#3572A5F",
        color:"#F9F4DA"
    },
     {
        name:"Node.js",
        backgroundColor:"#701516",
        color:"#F9F4DA"
    },
     {
        name:"Python",
        backgroundColor:"#4F5D95",
        color:"#F9F4DA"
    },
     {
        name:"Ruby",
        backgroundColor:"#00ADD8",
        color:"#F9F4DA"
    },
     {
        name:"Assembly",
        backgroundColor:"#dea584",
        color:"#F9F4DA"
    },
]